name: practice workflow

jobs: 
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name:  say hello
              run: echo "hello, world"
              
            - name: show current date and time 
              run: date  
            
            - name: show current direcrtory
              run: pwd

on: 
    push:
        branches:
            - main 